COMPANY_LIST = [
    '3M Company',
    'Abbott Laboratories',
    'AbbVie',
    'ABIOMED Inc',
    'Accenture plc',
    'Activision Blizzard',
    'Adobe',
    'Advanced Micro Devices Inc',
    'Advance Auto Parts',
    'AES Corp',
    'AFLAC Inc',
    'Agilent Technologies Inc',
    'Air Products & Chemicals Inc',
    'Akamai Technologies Inc',
    'Alaska Air Group Inc',
    'Albemarle Corp',
    'Alexandria Real Estate Equities',
    'Alexion Pharmaceuticals',
    'Align Technology',
    'Allegion',
    'Alliant Energy Corp',
    'Allstate Corp',
    'Alphabet',
    'Altria Group Inc',
    'Amazoncom',
    'Amcor plc',
    'Ameren Corp',
    'American Airlines Group',
    'American Electric Power',
    'American Express Co',
    'American International Group',
    'American Tower',
    'American Water Works Company Inc',
    'Ameriprise Financial',
    'AmerisourceBergen Corp',
    'AMETEK',
    'Amgen',
    'Amphenol Corp',
    'Analog Devices',
    'ANSYS',
    'Anthem',
    'Aon plc',
    'AO Smith Corp',
    'Apache Corporation',
    'Apple',
    'Applied Materials',
    'Aptiv PLC',
    'Archer-Daniels-Midland Co',
    'Arista Networks',
    'Arthur J Gallagher & Co',
    'Assurant',
    'AT&T',
    'Atmos Energy',
    'Autodesk',
    'Automatic Data Processing',
    'AutoZone Inc',
    'AvalonBay Communities',
    'Avery Dennison Corp',
    'Baker Hughes Co',
    'Ball Corp',
    'Bank of America Corp',
    'The Bank of New York Mellon',
    'Baxter International',
    'Becton Dickinson',
    'Berkshire Hathaway',
    'Best Buy Co',
    'Bio-Rad Laboratories',
    'Biogen',
    'BlackRock',
    'Boeing Company',
    'Booking Holdings Inc',
    'BorgWarner',
    'Boston Properties',
    'Boston Scientific',
    'Bristol-Myers Squibb',
    'Broadcom',
    'Broadridge Financial Solutions',
    'Brown-Forman',
    'C H Robinson Worldwide',
    'Cabot Oil & Gas',
    'Cadence Design Systems',
    'Campbell Soup',
    'Capital One Financial',
    'Cardinal Health',
    'Carmax Inc',
    'Carnival',
    'Carrier Global',
    'Catalent',
    'Caterpillar',
    'Cboe Global Markets',
    'CBRE Group',
    'CDW',
    'Celanese',
    'Centene Corporation',
    'CenterPoint Energy',
    'Cerner',
    'CF Industries Holdings Inc',
    'Charles Schwab Corporation',
    'Charter Communications',
    'Chevron',
    'Chipotle Mexican Grill',
    'Chubb Limited',
    'Church & Dwight',
    'CIGNA',
    'Cincinnati Financial',
    'Cintas Corporation',
    'Cisco Systems',
    'Citigroup',
    'Citizens Financial Group',
    'Citrix Systems',
    'The Clorox Company',
    'CME Group',
    'CMS Energy',
    'Coca-Cola Company',
    'Cognizant Technology Solutions',
    'Colgate-Palmolive',
    'Comcast',
    'Comerica',
    'Conagra Brands',
    'Concho Resources',
    'ConocoPhillips',
    'Consolidated Edison',
    'Constellation Brands',
    'The Cooper Companies',
    'Copart Inc',
    'Corning',
    'Corteva',
    'Costco Wholesale',
    'Crown Castle International',
    'CSX',
    'Cummins',
    'CVS Health',
    'D R Horton',
    'Danaher',
    'Darden Restaurants',
    'DaVita',
    'Deere & Co',
    'Delta Air Lines',
    'Dentsply Sirona',
    'Devon Energy',
    'DexCom',
    'Diamondback Energy',
    'Digital Realty Trust Inc',
    'Discover Financial Services',
    'Discovery ',
    'Dish Network',
    'Dollar General',
    'Dollar Tree',
    'Dominion Energy',
    'Dominos Pizza',
    'Dover Corporation',
    'Dow',
    'DTE Energy Co',
    'Duke Energy',
    'Duke Realty Corp',
    'DuPont de Nemours Inc',
    'DXC Technology',
    'Eastman Chemical',
    'Eaton Corporation',
    'eBay',
    'Ecolab',
    'Edison Intl',
    'Edwards Lifesciences',
    'Electronic Arts',
    'Emerson Electric Company',
    'Entergy',
    'EOG Resources',
    'Equifax',
    'Equinix',
    'Equity Residential',
    'Essex Property Trust',
    'Estée Lauder Companies',
    'Etsy',
    'Evergy',
    'Eversource Energy',
    'Everest Re Group Ltd',
    'Exelon',
    'Expedia Group',
    'Expeditors',
    'Extra Space Storage',
    'Exxon Mobil',
    'F5 Networks',
    'Facebook',
    'Fastenal Co',
    'Federal Realty Investment Trust',
    'FedEx Corporation',
    'Fidelity National Information Services',
    'Fifth Third Bancorp',
    'FirstEnergy Corp',
    'First Republic Bank',
    'Fiserv Inc',
    'FleetCor Technologies Inc',
    'FLIR Systems',
    'Flowserve Corporation',
    'FMC Corporation',
    'Ford Motor Company',
    'Fortinet',
    'Fortive Corp',
    'Fortune Brands Home & Security',
    'Fox Corporation ',
    'Franklin Resources',
    'Freeport-McMoRan',
    'Gap',
    'Garmin Ltd',
    'Gartner Inc',
    'General Dynamics',
    'General Electric',
    'General Mills',
    'General Motors',
    'Genuine Parts',
    'Gilead Sciences',
    'Globe Life',
    'Global Payments',
    'Goldman Sachs Group',
    'Grainger (WW)',
    'Halliburton Co',
    'Hanesbrands Inc',
    'Hartford Financial SvcGp',
    'Hasbro',
    'HCA Healthcare',
    'Healthpeak Properties',
    'Henry Schein',
    'The Hershey Company',
    'Hess Corporation',
    'Hewlett Packard Enterprise',
    'Hilton Worldwide Holdings Inc',
    'HollyFrontier Corp',
    'Hologic',
    'Home Depot',
    'Honeywell Intl',
    'Hormel Foods',
    'Host Hotels & Resorts',
    'Howmet Aerospace',
    'HP',
    'Humana',
    'Huntington Bancshares',
    'Huntington Ingalls Industries',
    'IDEX Corporation',
    'IDEXX Laboratories',
    'IHS Markit Ltd',
    'Illinois Tool Works',
    'Illumina Inc',
    'Incyte',
    'Ingersoll Rand',
    'Intel',
    'Intercontinental Exchange',
    'International Business Machines',
    'International Paper',
    'Interpublic Group',
    'International Flavors & Fragrances',
    'Intuit',
    'Intuitive Surgical',
    'Invesco Ltd',
    'IPG Photonics',
    'IQVIA Holdings',
    'Iron Mountain Incorporated',
    'Jack Henry & Associates',
    'Jacobs Engineering Group',
    'J B Hunt Transport Services',
    'JM Smucker',
    'Johnson & Johnson',
    'Johnson Controls International',
    'JPMorgan Chase & Co',
    'Juniper Networks',
    'Kansas City Southern',
    'Kellogg Co',
    'KeyCorp',
    'Keysight Technologies',
    'Kimberly-Clark',
    'Kimco Realty',
    'Kinder Morgan',
    'KLA Corporation',
    'Kraft Heinz Co',
    'Kroger Co',
    'L Brands',
    'L3Harris Technologies',
    'Laboratory of America Holding',
    'Lam Research',
    'Lamb Weston Holdings Inc',
    'Las Vegas Sands',
    'Leggett & Platt',
    'Leidos Holdings',
    'Lennar',
    'Lilly (Eli) & Co',
    'Lincoln National',
    'Linde plc',
    'Live Nation Entertainment',
    'LKQ Corporation',
    'Lockheed Martin',
    'Loews',
    'Lowes Cos',
    'Lumen Technologies',
    'LyondellBasell',
    'M&T Bank',
    'Marathon Oil',
    'Marathon Petroleum',
    'MarketAxess',
    'Marriott Intl',
    'Marsh & McLennan',
    'Martin Marietta Materials',
    'Masco',
    'Mastercard',
    'McCormick & Co',
    'Maxim Integrated Products Inc',
    'McDonalds',
    'McKesson',
    'Medtronic plc',
    'Merck & Co',
    'MetLife',
    'Mettler Toledo',
    'MGM Resorts International',
    'Microchip Technology',
    'Micron Technology',
    'Microsoft',
    'Mid-America Apartments',
    'Mohawk Industries',
    'Molson Coors Beverage Company',
    'Mondelez International',
    'Monster Beverage',
    'Moodys Corp',
    'Morgan Stanley',
    'The Mosaic Company',
    'Motorola Solutions',
    'MSCI Inc',
    'Nasdaq',
    'NetApp',
    'Netflix',
    'Newell Brands',
    'Newmont Corporation',
    'News Class A',
    'News Class B',
    'NextEra Energy',
    'Nielsen Holdings',
    'Nike',
    'NiSource',
    'Norfolk Southern',
    'Northern Trust',
    'Northrop Grumman',
    'NortonLifeLock',
    'Norwegian Cruise Line Holdings',
    'NOV',
    'NRG Energy',
    'Nucor',
    'Nvidia Corporation',
    'NVR',
    'OReilly Automotive',
    'Occidental Petroleum',
    'Old Dominion Freight Line',
    'Omnicom Group',
    'ONEOK',
    'Oracle',
    'Otis Worldwide',
    'PACCAR',
    'Packaging Corporation of America',
    'Parker-Hannifin',
    'Paychex',
    'Paycom',
    'PayPal',
    'Pentair plc',
    'Peoples United Financial',
    'PepsiCo',
    'PerkinElmer',
    'Perrigo',
    'Pfizer',
    'Philip Morris International',
    'Phillips 66',
    'Pinnacle West Capital',
    'Pioneer Natural Resources',
    'PNC Financial Services',
    'Pool Corporation',
    'PPG Industries',
    'PPL',
    'Principal Financial Group',
    'Procter & Gamble',
    'Progressive',
    'Prologis',
    'Prudential Financial',
    'Public Service Enterprise Group (PSEG)',
    'Public Storage',
    'PulteGroup',
    'PVH',
    'Qorvo',
    'Quanta Services',
    'QUALCOMM',
    'Quest Diagnostics',
    'Ralph Lauren Corporation',
    'Raymond James Financial',
    'Raytheon Technologies',
    'Realty Income Corporation',
    'Regency Centers Corporation',
    'Regeneron Pharmaceuticals',
    'Regions Financial',
    'Republic Services Inc',
    'ResMed',
    'Robert Half International',
    'Rockwell Automation',
    'Rollins',
    'Roper Technologies',
    'Ross Stores',
    'Royal Caribbean Group',
    'S&P Global',
    'Salesforcecom',
    'SBA Communications',
    'Schlumberger Ltd',
    'Seagate Technology',
    'Sealed Air',
    'Sempra Energy',
    'ServiceNow',
    'Sherwin-Williams',
    'Simon Property Group Inc',
    'Skyworks Solutions',
    'SL Green Realty',
    'Snap-on',
    'Southern Company',
    'Southwest Airlines',
    'Stanley Black & Decker',
    'Starbucks',
    'State Street',
    'STERIS plc',
    'Stryker',
    'SVB Financial',
    'Synchrony Financial',
    'Synopsys',
    'Sysco',
    'T-Mobile US',
    'T Rowe Price Group',
    'Take-Two Interactive',
    'Tapestry',
    'Target',
    'TE Connectivity Ltd',
    'TechnipFMC',
    'Teledyne Technologies',
    'Teleflex',
    'Teradyne',
    'Tesla',
    'Texas Instruments',
    'Textron',
    'Thermo Fisher Scientific',
    'Tiffany & Co',
    'TJX Companies',
    'Tractor Supply Company',
    'Trane Technologies plc',
    'TransDigm Group',
    'The Travelers Companies',
    'Truist Financial',
    'Twitter',
    'Tyler Technologies',
    'Tyson Foods',
    'UDR',
    'Ulta Beauty',
    'US Bancorp',
    'Under Armour ',
    'Union Pacific Corp',
    'United Airlines Holdings',
    'UnitedHealth Group',
    'United Parcel Service',
    'United Rentals',
    'Universal Health Services',
    'Unum Group',
    'Valero Energy',
    'Varian Medical Systems',
    'Ventas Inc',
    'Verisign',
    'Verisk Analytics',
    'Verizon Communications',
    'Vertex Pharmaceuticals Inc',
    'VF Corporation',
    'ViacomCBS',
    'Viatris',
    'Visa',
    'Vontier',
    'Vornado Realty Trust',
    'Vulcan Materials',
    'W R Berkley Corporation',
    'Westinghouse Air Brake Technologies Corp',
    'Walmart',
    'Walgreens Boots Alliance',
    'The Walt Disney Company',
    'Waste Management',
    'Waters Corporation',
    'WEC Energy Group',
    'Wells Fargo',
    'Welltower',
    'West Pharmaceutical Services',
    'Western Digital',
    'Western Union Co',
    'WestRock',
    'Weyerhaeuser',
    'Whirlpool',
    'Williams Companies',
    'Willis Towers Watson',
    'Wynn Resorts Ltd',
    'Xcel Energy Inc',
    'Xerox',
    'Xilinx',
    'Xylem',
    'Yum! Brands Inc',
    'Zebra Technologies',
    'Zimmer Biomet',
    'Zions Bancorp',
    'Zoetis'
]
